---
title: "Summarise CPUE data"
author: "Max Lindmark"
date: today
date-format: iso
toc: true
format: 
  html:
    page-layout: full
    embed-resources: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%
editor: source
---

## Load libraries

```{r}
#| message: false
#| warnings: false

library(tidyverse)
library(tidyterra)
library(tidylog)
library(tidync)
library(sdmTMB)
library(devtools)
library(nls.multstart)
library(broom)
library(nlstools)
library(ncdf4)
library(ggsidekick)
theme_set(theme_sleek())

# Set path 
home <- here::here()
```

## Read data

```{r}
#| message: false
#| warnings: false

d <- read_csv(paste0(home, "/data/clean/cpue_length.csv")) |> 
  filter(year >= 1993)
```

For plaice we only have age at maturity, not size, so let's fit a quick VBGE model to calculate size-at-maturity, before we continue processing the catch data.

```{r fit vbgf}
#| message: false
#| warnings: false

bits_ca <- read_csv(paste0(home, "/data/datras/bits_ca.csv"))
tax <- read_csv("https://raw.githubusercontent.com/maxlindmark/BITS/refs/heads/main/output/taxa.csv")

plaice <- bits_ca |> 
  left_join(tax, by = c("SpecCodeType", "SpecCode")) |> 
  filter(latin_name == "Pleuronectes platessa") |>  
  mutate(length_cm = LngtClass,
         length_cm = ifelse(LngtCode %in% c("0", "."), length_cm/10, length_cm)) |>  
  drop_na(Age) |>  
  rename(age = Age) |>  
  filter(age < 25 & age > 0) |> 
  filter(length_cm < 120) |> 
  filter(length_cm > 2)

# Now I need to copy rows with NoAtLngt > 1 so that 1 row = 1 ind
plaice <- plaice %>% map_df(., rep, .$CANoAtLngt)

ggplot(plaice, aes(factor(age), length_cm)) +
  geom_jitter()

# Fit VBGE models

VBGF <- function(age,Linf,k) { 
  Linf*(1 - exp(-k*(age))) 
}

fit <- nls_multstart(length_cm ~ VBGF(age, Linf, k),
                     data = plaice,
                     iter = 500,
                     start_lower = c(Linf = 10, k = 0.1),
                     start_upper = c(Linf = 70, k = 0.6),
                     supp_errors = 'Y')

preds <- augment(fit)

# Size at age 2?
predict(fit, newdata = data.frame(age = 2))

ggplot() +
  geom_jitter(data = plaice, aes(factor(age), length_cm), alpha = 0.4, height = 0) +
  geom_line(data = preds, aes(age, .fitted), color = "tomato3", linewidth = 1)

# Now do whiting
whiting <- bits_ca |>
  left_join(tax, by = c("SpecCodeType", "SpecCode")) |>
  filter(latin_name == "Merlangius merlangus") |>
  mutate(length_cm = LngtClass,
         length_cm = ifelse(LngtCode %in% c("0", "."), length_cm/10, length_cm)) |>
  drop_na(Age) |>
  rename(age = Age)

# Now I need to copy rows with NoAtLngt > 1 so that 1 row = 1 ind
whiting <- whiting %>% map_df(., rep, .$CANoAtLngt)

ggplot(whiting, aes(factor(age), length_cm)) +
  geom_jitter(alpha = 0.4, height = 0)

# Fit VBGE models
fit <- nls_multstart(length_cm ~ VBGF(age, Linf, k),
                     data = whiting,
                     iter = 500,
                     start_lower = c(Linf = 30, k = 0.05),
                     start_upper = c(Linf = 70, k = 0.6),
                     supp_errors = 'Y')

preds <- augment(fit)

# Size at age 2?
predict(fit, newdata = data.frame(age = 2))

ggplot() +
  geom_jitter(data = whiting, aes(factor(age), length_cm), alpha = 0.4, height = 0) +
  geom_line(data = preds, aes(age, .fitted), color = "tomato3", linewidth = 1)
```

```{r}
#| message: false
#| warnings: false

# d |>
#   filter(species == "Gadus morhua") |>
#   filter(year %in% c(1993, 2003, 2011, 2021)) |>
#   filter(density > 0) |>
#   mutate(density_round = round(density)) |>
#   uncount(density_round) |>
#   ggplot(aes(length_class, fill = as.factor(year), color = as.factor(year))) +
#   geom_density(fill = NA)
# 
# library(ggridges)
# library(RColorBrewer)
# library(viridis)
# 
# d |>
#   filter(species == "Gadus morhua") |>
#   filter(year %in% c(1993, 2003, 2011, 2021)) |>
#   filter(density > 0) |>
#   mutate(density_round = round(density)) |>
#   uncount(density_round) |>
#   ggplot(aes(x = length_class, y = as.factor(year),
#              fill = after_stat(x > 35))) +
#   theme_sleek(base_size = 17) +
#   geom_density_ridges_gradient(scale = 1, alpha = 0.2) +
#   scale_y_discrete(expand = c(0, 0), limits = rev) +
#   scale_x_continuous(expand = c(0, 0)) +
#   guides(fill = "none", color = "none") +
#   labs(y = "Year", x = "Length (cm)") +
#   scale_fill_manual(values = c("gray80", "skyblue")) +
#   NULL
# 
# ggsave(paste0(home, "/figures/NV/spatial_trends.pdf"), width = 13, height = 12, units = "cm")
# d |> 
#   filter(species == "Gadus morhua") |> 
#   filter(density > 0) |> 
#   summarise(lwr = quantile(length_class, prob = 0.25),
#             median = quantile(length_class, prob = 0.5),
#             upr = quantile(length_class, prob = 0.75),
#             .by = c(year, species)) |> 
#   pivot_longer(c(-year, -species)) |> 
#   ggplot(aes(year, value, linetype = name)) +  
#   geom_line() + 
#   facet_wrap(~species, scales = "free")
```  

```{r}
#| message: false
#| warnings: false

# Add in maturity stage
unique(d$species)

d <- d |>  
  mutate(maturation_size = NA,
         maturation_size = ifelse(species == "Gadus morhua", 30, maturation_size), # Lindmark 2020, van Leeuven 2013, note ofc this has changed over time...
         maturation_size = ifelse(species == "Platichthys flesus", 19, maturation_size), # Erlandsson 2017 (median L50)
         maturation_size = ifelse(species == "Pleuronectes platessa", 21, maturation_size), # Estimated above based on WGBFAS 50% of 2 year olds being mature
         maturation_size = ifelse(species == "Limanda limanda", 18, maturation_size), # Stock Annex: Dab (Limanda limanda) in subdivisions 22–32 (Baltic Sea)
         maturation_size = ifelse(species == "Psetta maxima", 18, maturation_size), # Helcom
         maturation_size = ifelse(species == "Merlangius merlangus", 24, maturation_size)) |> # Estimated above based age at maturity of 2-3 year olds (Helcom)
  mutate(life_stage = ifelse(length_cm >= maturation_size, "adult", "juvenile"))

lw_pars <- d |> 
  drop_na(aL, b) |> 
  summarise(a = mean(aL),
            b = mean(b), .by = species)

max_size <- d |> 
  filter(density > 0) |> 
  summarise(max_length = quantile(length_cm, 0.999), .by = species)

mat_size <- tibble(
  species = c("Gadus morhua",
              "Platichthys flesus", 
              "Pleuronectes platessa", 
              "Limanda limanda", 
              "Psetta maxima",
              "Merlangius merlangus"),
  mat_length = c(30, 19, 21, 18, 18, 24) 
)

sizes <- tibble(
  expand_grid(
    species = unique(d$species),
    life_stage = c("adult", "juvenile"),
  )) |> 
  left_join(max_size, by = "species") |> 
  left_join(mat_size, by = "species") |>
  left_join(lw_pars, by = "species") |> 
  left_join(tax |> distinct(latin_name, common_name), by = c("species" = "latin_name")) |> 
  mutate(min_length = 10) |> 
  # representative sizes (geometric mean)
  mutate(rep_length = ifelse(life_stage == "adult",
                             (mat_length*max_length)^0.5,
                             (min_length*mat_length)^0.5)) |> 
  # This because we combine all sizes
  mutate(rep_length = ifelse(common_name %in% c("dab", "turbot", "whiting"),
                             (min_length*max_length)^0.5,
                             rep_length)) |> 
  mutate(life_stage = ifelse(common_name %in% c("dab", "turbot", "whiting"),
                             "all", life_stage)) |> 
  mutate(B = round(a*rep_length^b, 0)) |> 
  distinct(species, life_stage, .keep_all = TRUE)

sizes

write_csv(sizes, paste0(home, "/data/clean/sizes.csv"))

# Summarize total density by haul, species, life stage
# If length_cm == NA, then life_stage will be NA, and the density of that group will be 0. But that is a 0 catch for both juveniles and adults.
# Therefore I will calculate the adult and juvenile biomass separately, then do the empty hauls (and dubplicate that by life stage)
d_sum <- d |>  
  drop_na(length_cm) |> 
  left_join(sizes |> distinct(species, mat_length)) |> 
  mutate(life_stage = ifelse(length_cm > mat_length, "adult", "juvenile")) |>
  summarise(density = sum(biomass_density), .by = c(haul_id, species, life_stage)) 

# In all hauls, I have a row with density = 0 and length_cm = NA. True empty catches are those with a total biomass density of 0, not if length_cm is NA!
d |> filter(density == 0) |> distinct(length_cm)
d |> filter(is.na(length_cm)) |> distinct(density)

empty_hauls <- d |>
  filter(is.na(length_cm)) |>
  mutate(life_stage = NA) |>
  distinct(haul_id, species) |> 
  replicate_df(time_name = "life_stage", time_values = c("adult", "juvenile")) |> 
  mutate(density = 0)

d_sum <- bind_rows(d_sum, empty_hauls) |> 
  left_join(tax |>
              dplyr::select(latin_name, common_name) |> 
              distinct(latin_name, common_name),
            by = c("species" = "latin_name")) |> 
  mutate(group = paste(common_name, life_stage, sep = "_")) |>  
  dplyr::select(-life_stage, -species)
  
# Now left join in all other information...
d_haul <- d |>  
  distinct(haul_id, .keep_all = TRUE) |>  
  dplyr::select(year, quarter, month, date, ices_rect, sub_div, lon, lat, haul_id)

d_sum <- d_sum |> left_join(d_haul, by = "haul_id")

# Check distributions of densities across hauls
d_sum |>  
  ggplot(aes(density)) + 
  geom_histogram() + 
  facet_wrap(~group, scales = "free", ncol = 3)

# Plot in space
d_sum |> 
  mutate(presence = ifelse(density == 0, "0", "1")) |> 
  ggplot(aes(lon, lat, color = presence)) +
  facet_wrap(~group) +
  geom_point(size = 0.25)

d_sum |> 
  summarise(sum = sum(density), .by = group) |> 
  ggplot(aes(sum, reorder(group, sum))) +
  geom_bar(stat = "identity")
  
# Based on this plot, I will collapse dab, whiting and turbot into a single group, and keep juvenile/adult distinction for cod, flounder and plaice
dwt <- d_sum |> 
  filter(common_name %in% c("dab", "whiting", "turbot")) |>
  mutate(density = sum(density), .by = c(haul_id, common_name)) |> 
  distinct(haul_id, .keep_all = TRUE) |> 
  mutate(group = paste(common_name, "all", sep = "_"))

d_sum <- d_sum |> 
  filter(!common_name %in% c("dab", "whiting", "turbot")) |> 
  bind_rows(dwt)

unique(d_sum$group)
```

## Add environmental covariates

```{r}
#| message: false
#| warnings: false

d_sum <- d_sum |> 
  mutate(year_month = paste(year, month, sep = "_"))

# Oxygen
# https://data.marine.copernicus.eu/product/BALTICSEA_MULTIYEAR_BGC_003_012/download?dataset=cmems_mod_bal_bgc_my_P1M-m_202303
# Print details
print(nc_open(paste0(home, "/data/covariates/cmems_mod_bal_bgc_my_P1M-m_1742291088556.nc")))

oxy_tibble <- tidync(paste0(home, "/data/covariates/cmems_mod_bal_bgc_my_P1M-m_1742291088556.nc")) |>
  hyper_tibble() |>
  mutate(date = as_datetime(time, origin = "1970-01-01")) |>
  mutate(
    month = month(date),
    day = day(date),
    year = year(date),
    oxy = o2b * 0.0223909
  )

# Salinity and temperature
# https://data.marine.copernicus.eu/product/BALTICSEA_MULTIYEAR_PHY_003_011/download?dataset=cmems_mod_bal_phy_my_P1M-m_202303
# Print details
print(nc_open(paste0(home, "/data/covariates/cmems_mod_bal_phy_my_P1M-m_1742290961273.nc")))

st_tibble <- tidync(paste0(home, "/data/covariates/cmems_mod_bal_phy_my_P1M-m_1742290961273.nc")) |>
  hyper_tibble() |>
  mutate(date = as_datetime(time, origin = "1970-01-01")) |>
  mutate(
    month = month(date),
    day = day(date),
    year = year(date)
  )

# env combined
env_comb <- st_tibble |> 
  left_join(oxy_tibble |> dplyr::select(longitude, latitude, oxy, year, month),
            by = c("longitude", "latitude", "year", "month")) |> 
  mutate(year_month = paste(year, month, sep = "_"))

# Loop through all year combos, extract the copernicus temperatures at the data locations of the trawl
env_list <- list()

for (i in unique(d_sum$year_month)) {

  d_sub <- filter(d_sum, year_month == i)
  env_sub <- filter(env_comb, year_month == i)

  # Convert to spat_raster
  env_raster <- as_spatraster(env_sub,
    xycols = 3:4,
    crs = "WGS84", digits = 3
  )

  # Extract from raster
  d_sub$temp <- terra::extract(
    env_raster$bottomT,
    d_sub |> dplyr::select(lon, lat)
  )$bottomT

  d_sub$sal <- terra::extract(
    env_raster$sob,
    d_sub |> dplyr::select(lon, lat)
  )$sob

  d_sub$oxy <- terra::extract(
    env_raster$oxy,
    d_sub |> dplyr::select(lon, lat)
  )$oxy

  # Save
  env_list[[i]] <- d_sub
}

dd <- bind_rows(env_list) |> drop_na(temp)
```

```{r}
#| message: false
#| warnings: false

# This is for the long time series with bias-correction to join old and new environmetal data
# env_vars <- read_csv(paste0(home, "/data/covariates/bias_corr_vars.csv"))
# 
# # Loop through all year-month combos, extract the variables at data locations
# d_list <- list()
# 
# d_sum$year_month <- paste(d_sum$year, d_sum$month, sep = "_")
# env_vars$year_month <- paste(env_vars$year, env_vars$month, sep = "_")
# 
# for (i in sort(unique(d_sum$year_month))) {
# 
#   d_sub <- filter(d_sum, year_month == i)
#   env_sub <- filter(env_vars, year_month == i)
# 
#   # Convert to spat_raster
#   env_raster <- as_spatraster(env_sub,
#     xycols = 1:2,
#     crs = "WGS84", digits = 3
#   )
# 
#   # Extract from raster
#   d_sub <- d_sub |> 
#     mutate(temp = terra::extract(env_raster$temp, d_sub |> dplyr::select(lon, lat))$temp,
#            sal = terra::extract(env_raster$sal, d_sub |> dplyr::select(lon, lat))$sal,
#            oxy = terra::extract(env_raster$oxy, d_sub |> dplyr::select(lon, lat))$oxy)
#   
#   # Save
#   d_list[[i]] <- d_sub
# }
# 
# dd <- bind_rows(d_list) |> drop_na(temp)
```

```{r}
#| message: false
#| warnings: false

# Add depth

# Add depth now to remove islands and remaining land
# https://gis.stackexchange.com/questions/411261/read-multiple-layers-raster-from-ncdf-file-using-terra-package
# https://emodnet.ec.europa.eu/geoviewer/
dep_raster <- terra::rast("/Users/maxlindmark/Dropbox/Max work/R/pred-prey-overlap/data/covariates/depth/Mean depth natural colour (with land).nc")
#crs(dep_raster, proj = TRUE)
#plot(dep_raster)

dd$depth <- terra::extract(dep_raster, dd |> dplyr::select(lon, lat))$elevation

ggplot(dd, aes(lon, lat, color = depth * -1)) +
  geom_point()

dd$depth <- dd$depth * -1

dd <- dd |> tidylog::drop_na(depth)
```

Save!

```{r}
# Save!
write_csv(dd, paste0(home, "/data/clean/catch_clean.csv"))
```
