---
title: "Make the prediction grid"
author: "Max Lindmark"
date: today
date-format: iso
toc: true
format: 
  html:
    page-layout: full
    embed-resources: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%
editor: source
---

## Intro
Make an evenly spaced UTM prediction grid with all spatially varying covariates for the diet and the biomass data

```{r lib}
#| message: false
#| warning: false

library(tidyverse)
library(tidyterra)
library(tidylog)
library(tidync)
library(sp)
library(raster)
library(devtools)
library(RCurl)
library(sdmTMB)
library(terra)
library(ncdf4)
library(chron)
library(ggsidekick)
theme_set(theme_sleek())

# Set path
home <- here::here()
```

Read data and depth-raster

```{r data}
#| message: false
#| warning: false

d <- read_csv(paste0(home, "/data/clean/cpue_length.csv")) |> 
  filter(year >= 1993)

d <- d |> add_utm_columns(ll_names = c("lon", "lat"))
```

## Make the grid with depth
First make a grid for the biomass data, then subset that based on the extend of the stomach data

```{r make pred grid}
#| message: false
#| warning: false

x <- d$X
y <- d$Y
z <- chull(x, y)

coords <- cbind(x[z], y[z])

coords <- rbind(coords, coords[1, ])

plot(coords[, 1] ~ coords[, 2]) # plot data

sp_poly <- sp::SpatialPolygons(
  list(sp::Polygons(list(sp::Polygon(coords)), ID = 1))
  )

sp_poly_df <- sp::SpatialPolygonsDataFrame(sp_poly,
                                           data = data.frame(ID = 1)
                                           )
cell_width <- 3

pred_grid <- expand.grid(
  X = seq(min(d$X), max(d$X), cell_width),
  Y = seq(min(d$Y), max(d$Y), cell_width),
  year = sort(unique(d$year))
  )

sp::coordinates(pred_grid) <- c("X", "Y")

inside <- !is.na(sp::over(pred_grid, as(sp_poly_df, "SpatialPolygons")))

pred_grid <- pred_grid[inside, ]

pred_grid <- as.data.frame(pred_grid)

ggplot(data = filter(pred_grid, year == 1999), aes(X*1000, Y*1000)) + 
  geom_point(size = 0.001, alpha = 0.5) +
  NULL

# Add lat and lon
# Need to go from UTM to lat long for this one...
# https://stackoverflow.com/questions/30018098/how-to-convert-utm-coordinates-to-lat-and-long-in-r
xy <- as.matrix(pred_grid |> dplyr::select(X, Y) |> mutate(X = X*1000, Y = Y*1000))
v <- vect(xy, crs="+proj=utm +zone=33 +datum=WGS84  +units=m")
y <- project(v, "+proj=longlat +datum=WGS84")
lonlat <- geom(y)[, c("x", "y")]

pred_grid$lon <- lonlat[, 1]
pred_grid$lat <- lonlat[, 2]

ggplot(filter(pred_grid, year == 1999), aes(lon, lat)) + geom_point()

# Add depth now to remove islands and remaining land
dep_raster <- terra::rast("/Users/maxlindmark/Dropbox/Max work/R/pred-prey-overlap/data/covariates/depth/Mean depth natural colour (with land).nc")

pred_grid$depth <- terra::extract(dep_raster, pred_grid |> dplyr::select(lon, lat))$elevation*-1

pred_grid <- pred_grid |> drop_na(depth)

pred_grid |> 
  filter(year == 1999) |> 
  drop_na(depth) |> 
  ggplot(aes(X*1000, Y*1000, fill = depth)) + 
  geom_raster() +
  NULL
```

## Add environmental covariates
#| message: false
#| warnings: false

```{r}
#| message: false
#| warning: false

# Add month_year variable for matching with raster layers

pred_grid <- pred_grid |>
  replicate_df(time_name = "month", time_values = c(2, 11)) |> 
  mutate(quarter = ifelse(month == 2, 1, 4)) |> 
  mutate(year_month = paste(year, month, sep = "_"))

# Oxygen
# https://data.marine.copernicus.eu/product/BALTICSEA_MULTIYEAR_BGC_003_012/download?dataset=cmems_mod_bal_bgc_my_P1M-m_202303
# Print details
print(nc_open(paste0(home, "/data/covariates/cmems_mod_bal_bgc_my_P1M-m_1742291088556.nc")))

oxy_tibble <- tidync(paste0(home, "/data/covariates/cmems_mod_bal_bgc_my_P1M-m_1742291088556.nc")) |>
  hyper_tibble() |>
  mutate(date = as_datetime(time, origin = "1970-01-01")) |>
  mutate(
    month = month(date),
    day = day(date),
    year = year(date),
    oxy = o2b * 0.0223909
  )

# Salinity and temperature
# https://data.marine.copernicus.eu/product/BALTICSEA_MULTIYEAR_PHY_003_011/download?dataset=cmems_mod_bal_phy_my_P1M-m_202303
# Print details
print(nc_open(paste0(home, "/data/covariates/cmems_mod_bal_phy_my_P1M-m_1742290961273.nc")))

st_tibble <- tidync(paste0(home, "/data/covariates/cmems_mod_bal_phy_my_P1M-m_1742290961273.nc")) |>
  hyper_tibble() |>
  mutate(date = as_datetime(time, origin = "1970-01-01")) |>
  mutate(
    month = month(date),
    day = day(date),
    year = year(date)
  )

# env combined
env_comb <- st_tibble |> 
  left_join(oxy_tibble |> dplyr::select(longitude, latitude, oxy, year, month),
            by = c("longitude", "latitude", "year", "month")) |> 
  mutate(year_month = paste(year, month, sep = "_"))

# Loop through all year combos, extract the copernicus temperatures at the data locations of the trawl
env_list <- list()

for (i in unique(pred_grid$year_month)) {

  d_sub <- filter(pred_grid, year_month == i)
  env_sub <- filter(env_comb, year_month == i)

  # Convert to spat_raster
  env_raster <- as_spatraster(env_sub,
    xycols = 3:4,
    crs = "WGS84", digits = 3
  )

  # Extract from raster
  d_sub$temp <- terra::extract(
    env_raster$bottomT,
    d_sub |> dplyr::select(lon, lat)
  )$bottomT

  d_sub$sal <- terra::extract(
    env_raster$sob,
    d_sub |> dplyr::select(lon, lat)
  )$sob

  d_sub$oxy <- terra::extract(
    env_raster$oxy,
    d_sub |> dplyr::select(lon, lat)
  )$oxy

  # Save
  env_list[[i]] <- d_sub
}

pred_grid_env <- bind_rows(env_list) |> drop_na(temp)
```

```{r}
#| message: false
#| warnings: false

# # This is for the long time series with bias-correction to join old and new environmetal data
# env_vars <- read_csv(paste0(home, "/data/covariates/bias_corr_vars.csv"))
# 
# # Loop through all year-month combos, extract the variables at data locations
# d_list <- list()
# 
# pred_grid$year_month <- paste(pred_grid$year, pred_grid$month, sep = "_")
# env_vars$year_month <- paste(env_vars$year, env_vars$month, sep = "_")
# 
# for (i in sort(unique(pred_grid$year_month))) {
# 
#   d_sub <- filter(pred_grid, year_month == i)
#   env_sub <- filter(env_vars, year_month == i)
# 
#   # Convert to spat_raster
#   env_raster <- as_spatraster(env_sub,
#     xycols = 1:2,
#     crs = "WGS84", digits = 3
#   )
# 
#   # Extract from raster
#   d_sub <- d_sub |> 
#     mutate(temp = terra::extract(env_raster$temp, d_sub |> dplyr::select(lon, lat))$temp,
#            sal = terra::extract(env_raster$sal, d_sub |> dplyr::select(lon, lat))$sal,
#            oxy = terra::extract(env_raster$oxy, d_sub |> dplyr::select(lon, lat))$oxy)
#   
#   # Save
#   d_list[[i]] <- d_sub
# }
# 
# pred_grid_env <- bind_rows(d_list) |> drop_na(temp)
```

## Save

```{r save}
#| message: false
#| warning: false

pred_grid_93_07 <- pred_grid_env |> filter(year >= 1993 & year <= 2007)
pred_grid_08_23 <- pred_grid_env |> filter(year >= 2008)

write_csv(pred_grid_93_07, file = paste0(home, "/data/clean/pred_grid_(1_2).csv"))
write_csv(pred_grid_08_23, file = paste0(home, "/data/clean/pred_grid_(2_2).csv"))
```
