---
title: "Calculate metabolic index velocities for each species"
author: "Max Lindmark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 12,
  fig.asp = 0.618,
  fig.align ='center'
)
```

# Intro
Main analysis: This scripts reads predictions grids with predicted biomass densities (01_x) and metabolic index parameter estimates (02_x), calculates metabolic indexes by species and life stage and metabolic index velocities.

```{r load libraries, message=FALSE, warning=TRUE}
# Load libraries, install if needed
library(tidyverse)
library(tidylog)
library(RCurl)
library(devtools)
library(sdmTMB)
library(rMR)
library(patchwork)
library(raster)
library(VoCC)
library(RColorBrewer)
library(viridis)
library(mapplots)

# Source code for plots
source_url("https://raw.githubusercontent.com/maxlindmark/spatial-metabolic-index/main/R/functions/map-plot.R")

theme_set(theme_plot())
```

```{r}
# Read predictions grids
d <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/spatial-metabolic-index/master/data/clean/pred_grid_(1_2).csv") %>% 
  filter(ices_rect %in% c("39G7", "39G8", "39G9",
                          "40G7", "40G8", "40G9",
                          "41G7", "41G8", "41G9")) %>% 
  filter(year < 2002) %>% 
  group_by(ices_rect, year) %>% 
  summarise(Temperature = mean(temp),
            Oxygen = mean(oxy)) %>% 
  ungroup() %>% 
  mutate(Longitude = ices.rect(ices_rect)$lon,
         Latitude = ices.rect(ices_rect)$lat) %>% 
  mutate(Temperature = ifelse(ices_rect == "41G7" & year %in% c(1999, 2000, 2001),
                              Temperature*0.9, 
                              Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year %in% c(1999, 2000, 2001),
                              Temperature*1.05, 
                              Temperature))

# Plot temperature values
ggplot(d, aes(Longitude, Latitude, fill = Temperature)) + 
  geom_raster() + 
  facet_wrap(~year, ncol = 3) + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) + 
  NULL

ggsave("figures/supp/velocity_1.png", width = 15, height = 15, units = "cm")


# Plot linear temp trends!
ggplot(d, aes(year, Temperature, color = ices_rect)) + 
  geom_point() + 
  stat_smooth(method = "lm", se = FALSE)

dt <- d %>%
  split(.$ices_rect) %>%
  purrr::map(~lm(Temperature ~ year, data = .x)) %>%
  purrr::map_df(broom::tidy, .id = 'ices_rect') %>%
  filter(term == "year") %>% 
  rename(Trend = estimate) %>% 
  mutate(Longitude = ices.rect(ices_rect)$lon,
         Latitude = ices.rect(ices_rect)$lat)

p1 <- ggplot(dt %>% rename(), aes(Longitude, Latitude, fill = Trend)) + 
  geom_raster() + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")

## Calculate velocities!
# Convert pred grid to raster stack
# https://gist.github.com/statnmap/a3eb564d06dee47f2d83eceac4212881
dv <- d %>% 
  group_split(year) %>% 
  map(~rasterFromXYZ(.x[, c("Longitude", "Latitude", "Temperature")])) %>% 
  stack()

plot(dv)
  
# Temporal trend
vt2 <- tempTrend(dv, th = 5) # th = Integer minimum number of observations in the series needed to calculate the trend at each cell.
  
plot(vt2)
points_trend <- rasterToPoints(vt2) %>% 
  as.data.frame() %>% 
  rename(Longitude = x, Latitude = y)

p_test <- ggplot(points_trend, aes(Longitude, Latitude, fill = slpTrends)) + 
  geom_raster() + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")

# Spatial gradient
vg2 <- spatGrad(dv, projected = TRUE)
  
# Climate velocity
gv2 <- gVoCC(vt2, vg2)
  
# (so that we can use ggplot)
points <- rasterToPoints(gv2)
  
# Make the points a dataframe for ggplot
dv2 <- data.frame(points) %>%
  rename(Longitude = x, Latitude = y, Velocity = voccMag, Angle = voccAng)

p2 <- ggplot(dv2, aes(Longitude, Latitude, fill = Velocity)) + 
  geom_raster() + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")

p3 <- ggplot(dv2, aes(Longitude, Latitude, fill = Angle)) + 
  geom_raster() + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")

(p1 + p_test) / (p2 + p3)

# Replot with facet
dd <- bind_rows(dv2 %>% rename(y = Velocity) %>% mutate(Variable = "Velocity"),
                dt %>% rename(y = Trend) %>% mutate(Variable = "Trend"))

ggplot(dd, aes(Longitude, Latitude, fill = y)) + 
  geom_raster() + 
  facet_wrap(~ Variable) + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line"),
        panel.spacing = unit(0.75, "lines")) + 
  coord_cartesian(expand = 0) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3", name = "")

ggsave("figures/supp/velocity_3.png", width = 15, height = 15, units = "cm")
```





Test with a dummy-example

```{r}
unique(d$ices_rect)

d2 <- d %>% 
  filter(year < 1998) %>% 
  mutate(Temperature = 5,
         
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1993, 4.8, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1994, 4.9, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1996, 5.1, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1997, 5.2, Temperature),
         
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1993, 5.2, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1994, 5.1, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1996, 4.9, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1997, 4.8, Temperature)) %>% 
  mutate(Temperature = Temperature + rnorm(0, sd = 0.05, n = 45))

# Plot temperature values
ggplot(d2, aes(Longitude, Latitude, fill = Temperature)) + 
  geom_raster() + 
  facet_wrap(~year, ncol = 3) + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) + 
  NULL

# Plot linear temp trends!
ggplot(d2, aes(year, Temperature, color = ices_rect)) + 
  geom_point() + 
  facet_wrap(~ices_rect) +
  stat_smooth(method = "lm", se = FALSE)

dt2 <- d2 %>%
  split(.$ices_rect) %>%
  purrr::map(~lm(Temperature ~ year, data = .x)) %>%
  purrr::map_df(broom::tidy, .id = 'ices_rect') %>%
  filter(term == "year") %>% 
  rename(Trend = estimate) %>% 
  mutate(Longitude = ices.rect(ices_rect)$lon,
         Latitude = ices.rect(ices_rect)$lat)

ggplot(dt2, aes(Longitude, Latitude, fill = Trend)) + 
  geom_tile(color = "grey40", size = 1) + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")

## Calculate velocities!
# Convert pred grid to raster stack
# https://gist.github.com/statnmap/a3eb564d06dee47f2d83eceac4212881
dv2 <- d2 %>% 
  group_split(year) %>% 
  map(~rasterFromXYZ(.x[, c("Longitude", "Latitude", "Temperature")])) %>% 
  stack()

plot(dv2)
  
# Temporal trend
vt22 <- tempTrend(dv2, th = 5) # th = Integer minimum number of observations in the series needed to calculate the trend at each cell.
  
plot(vt22)
points_trend <- rasterToPoints(vt22) %>% 
  as.data.frame() %>% 
  rename(Longitude = x, Latitude = y)

# Spatial gradient
vg22 <- spatGrad(dv2, projected = TRUE)
  
# Climate velocity
gv22 <- gVoCC(vt22, vg22)
  
# (so that we can use ggplot)
points2 <- rasterToPoints(gv22)
  
# Make the points a dataframe for ggplot
dv22 <- data.frame(points2) %>%
  rename(Longitude = x, Latitude = y, Velocity = voccMag, Angle = voccAng)

ggplot(dv22, aes(Longitude, Latitude, fill = Velocity)) + 
  geom_raster() + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")
```

Test 2 with a dummy-example

```{r}
unique(d$ices_rect)
ggplot(d, aes(Longitude, Latitude, fill = ices_rect)) + 
  geom_raster()

d2 <- d %>% 
  filter(year < 1998) %>% 
  mutate(Temperature = 5,
         
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1993, 4.5, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1994, 4.75, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1996, 5.25, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1997, 5.5, Temperature),
         
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1993, 4.5, Temperature),
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1994, 4.75, Temperature),
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1996, 5.25, Temperature),
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1997, 5.5, Temperature),
         
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1993, 4.5, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1994, 4.75, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1996, 5.25, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1997, 5.5, Temperature),
         
         Temperature = ifelse(ices_rect == "40G8" & year == 1993, 3, Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year == 1994, 4, Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year == 1996, 6, Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year == 1997, 7, Temperature),
         ) %>% 
  mutate(Temperature = Temperature + rnorm(0, sd = 0.00001, n = 45))

# Plot temperature values
ggplot(d2, aes(Longitude, Latitude, fill = Temperature)) + 
  geom_raster() + 
  facet_wrap(~year, ncol = 3) + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) + 
  NULL

# Plot linear temp trends!
ggplot(d2, aes(year, Temperature, color = ices_rect)) + 
  geom_point() + 
  facet_wrap(~ices_rect) +
  stat_smooth(method = "lm", se = FALSE)

dt2 <- d2 %>%
  split(.$ices_rect) %>%
  purrr::map(~lm(Temperature ~ year, data = .x)) %>%
  purrr::map_df(broom::tidy, .id = 'ices_rect') %>%
  filter(term == "year") %>% 
  rename(Trend = estimate) %>% 
  mutate(Longitude = ices.rect(ices_rect)$lon,
         Latitude = ices.rect(ices_rect)$lat)

ggplot(dt2, aes(Longitude, Latitude, fill = Trend)) + 
  geom_tile(color = "grey40", size = 1) + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")

## Calculate velocities!
# Convert pred grid to raster stack
# https://gist.github.com/statnmap/a3eb564d06dee47f2d83eceac4212881
dv2 <- d2 %>% 
  group_split(year) %>% 
  map(~rasterFromXYZ(.x[, c("Longitude", "Latitude", "Temperature")])) %>% 
  stack()

plot(dv2)
  
# Temporal trend
vt22 <- tempTrend(dv2, th = 5) # th = Integer minimum number of observations in the series needed to calculate the trend at each cell.
  
plot(vt22)
points_trend <- rasterToPoints(vt22) %>% 
  as.data.frame() %>% 
  rename(Longitude = x, Latitude = y)

# Spatial gradient
vg22 <- spatGrad(dv2, projected = TRUE)
  
# Climate velocity
gv22 <- gVoCC(vt22, vg22)
  
# (so that we can use ggplot)
points2 <- rasterToPoints(gv22)
  
# Make the points a dataframe for ggplot
dv22 <- data.frame(points2) %>%
  rename(Longitude = x, Latitude = y, Velocity = voccMag, Angle = voccAng)

ggplot(dv22, aes(Longitude, Latitude, fill = Velocity)) + 
  geom_raster() + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")
```

Test 3 with a dummy-example

```{r}
unique(d$ices_rect)
ggplot(d, aes(Longitude, Latitude, fill = ices_rect)) + 
  geom_raster()

d2 <- d %>% 
  filter(year < 1998) %>% 
  mutate(Temperature = 5,
         
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1993, 3, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1994, 4, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1996, 6, Temperature),
         Temperature = ifelse(ices_rect %in% c("39G7", "39G8", "39G9") & year == 1997, 7, Temperature),
         
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1993, 3, Temperature),
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1994, 4, Temperature),
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1996, 6, Temperature),
         Temperature = ifelse(ices_rect %in% c("40G7", "40G9") & year == 1997, 7, Temperature),
         
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1993, 3, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1994, 4, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1996, 6, Temperature),
         Temperature = ifelse(ices_rect %in% c("41G7", "41G8", "41G9") & year == 1997, 7, Temperature),
         
         Temperature = ifelse(ices_rect == "40G8" & year == 1993, 4.5, Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year == 1994, 4.75, Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year == 1995, 5, Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year == 1996, 5.25, Temperature),
         Temperature = ifelse(ices_rect == "40G8" & year == 1997, 5.5, Temperature),
         ) %>% 
  mutate(Temperature = Temperature + rnorm(0, sd = 0.01, n = 45))

# Plot temperature values
ggplot(d2, aes(Longitude, Latitude, fill = Temperature)) + 
  geom_raster() + 
  facet_wrap(~year, ncol = 3) + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) + 
  NULL

# Plot linear temp trends!
ggplot(d2, aes(year, Temperature, color = ices_rect)) + 
  geom_point() + 
  facet_wrap(~ices_rect) +
  stat_smooth(method = "lm", se = FALSE)

dt2 <- d2 %>%
  split(.$ices_rect) %>%
  purrr::map(~lm(Temperature ~ year, data = .x)) %>%
  purrr::map_df(broom::tidy, .id = 'ices_rect') %>%
  filter(term == "year") %>% 
  rename(Trend = estimate) %>% 
  mutate(Longitude = ices.rect(ices_rect)$lon,
         Latitude = ices.rect(ices_rect)$lat)

ggplot(dt2, aes(Longitude, Latitude, fill = Trend)) + 
  geom_tile(color = "grey40", size = 1) + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")

## Calculate velocities!
# Convert pred grid to raster stack
# https://gist.github.com/statnmap/a3eb564d06dee47f2d83eceac4212881
dv2 <- d2 %>% 
  group_split(year) %>% 
  map(~rasterFromXYZ(.x[, c("Longitude", "Latitude", "Temperature")])) %>% 
  stack()

plot(dv2)
  
# Temporal trend
vt22 <- tempTrend(dv2, th = 5) # th = Integer minimum number of observations in the series needed to calculate the trend at each cell.
  
plot(vt22)
points_trend <- rasterToPoints(vt22) %>% 
  as.data.frame() %>% 
  rename(Longitude = x, Latitude = y)

# Spatial gradient
vg22 <- spatGrad(dv2, projected = TRUE)
  
# Climate velocity
gv22 <- gVoCC(vt22, vg22)
  
# (so that we can use ggplot)
points2 <- rasterToPoints(gv22)
  
# Make the points a dataframe for ggplot
dv22 <- data.frame(points2) %>%
  rename(Longitude = x, Latitude = y, Velocity = voccMag, Angle = voccAng)

ggplot(dv22, aes(Longitude, Latitude, fill = Velocity)) + 
  geom_raster() + 
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.key.height = unit(1, "line"),
        legend.key.width = unit(2.5, "line")) + 
  coord_cartesian(expand = 0) +
  scale_fill_viridis(option = "A", alpha = 0.9) +
  scale_fill_gradient2(low = "#56B1F7", high = "tomato3")
```








