---
title: "Plot conditional effects and grid predictions from 02"
author: "Max Lindmark"
date: today
date-format: iso
toc: true
format: 
  html:
    page-layout: full
    embed-resources: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%
editor: source
---

## Intro

Plot conditional effects from predictions in script "02-fit-sdms-conditional.qmd"

## Load packages & source functions

```{r load libraries}
#| message: false
#| warning: false

# Load libraries, install if needed
library(tidyverse)
library(readxl)
library(tidylog)
library(RCurl)
library(devtools)
library(patchwork)
library(viridis)
library(RColorBrewer)
library(here)
library(ggnewscale)
library(ggh4x)
library(egg)
library(concaveman)

devtools::source_url("https://raw.githubusercontent.com/maxlindmark/spatial-metabolic-index/main/R/functions/map-plot.R")
options(ggplot2.continuous.colour = "viridis")

pal_temp <- brewer.pal(n = 10, name = "Paired")[c(2, 6)]
pal_oxy <- brewer.pal(n = 10, name = "Paired")[c(8, 4)]

# Set path
home <- here::here()
```

## Read predictions

```{r}
#| warning: false
#| message: false

preds <- read_csv(paste0(home, "/output/conditional_02_sdms.csv")) |> 
  filter(oxy > 3 & oxy < 9) |>
  filter(temp > 2 & temp < 14) |>
  separate(group, c("species", "life_stage"), sep = "_", remove = FALSE) |> 
  mutate(species = str_to_title(species),
         life_stage = str_to_title(life_stage),
         group2 = paste(species, life_stage),
         group2 = factor(group2, 
                         levels = c("Cod Adult", "Cod Juvenile", "Flounder Adult", "Flounder Juvenile",
                                    "Plaice Adult", "Plaice Juvenile", "Dab All"))) |> 
  mutate(est_sc = exp(est)/max(exp(est)),
         .by = group)  # for plotting all together in heatmap

grid_preds <- read_csv(paste0(home, "/output/pred_grids_02_sdms.csv")) |>
  separate(group, c("species", "life_stage"), sep = "_", remove = FALSE) |> 
  mutate(species = str_to_title(species),
         life_stage = str_to_title(life_stage),
         group2 = paste(species, life_stage),
         group2 = factor(group2, 
                         levels = c("Cod Adult", "Cod Juvenile", "Flounder Adult", "Flounder Juvenile",
                                    "Plaice Adult", "Plaice Juvenile", "Dab All"))) |> 
  mutate(est = exp(est1 + est2))

cogs <- read_csv(paste0(home, "/output/cogs_02_sdms.csv")) |> 
  separate(group, c("species", "life_stage"), sep = "_", remove = FALSE) |> 
  mutate(species = str_to_title(species),
         life_stage = str_to_title(life_stage))

eaos <- read_csv(paste0(home, "/output/eaos_02_sdms.csv")) |>
  separate(group, c("species", "life_stage"), sep = "_", remove = FALSE) |>
  mutate(species = str_to_title(species),
         life_stage = str_to_title(life_stage),
         group2 = paste(species, life_stage),
         group2 = factor(group2,
                         levels = c("Cod Adult", "Cod Juvenile", "Flounder Adult", "Flounder Juvenile",
                                    "Plaice Adult", "Plaice Juvenile", "Dab All")))

index <- read_csv(paste0(home, "/output/index_02_sdms.csv")) |> 
  separate(group, c("species", "life_stage"), sep = "_", remove = FALSE) |> 
  mutate(species = str_to_title(species),
         life_stage = str_to_title(life_stage),
         group2 = paste(species, life_stage),
         group2 = factor(group2, 
                         levels = c("Cod Adult", "Cod Juvenile", "Flounder Adult", "Flounder Juvenile",
                                    "Plaice Adult", "Plaice Juvenile", "Dab All")))
```

```{r}
index <- index |> filter(!group == "dab_all")
cogs <- cogs |> filter(!group == "dab_all")
grid_preds <- grid_preds |> filter(!group == "dab_all")
preds <- preds |> filter(!group == "dab_all")
```

## Calculate weighted quantiles

```{r}
#| warning: false
#| message: false

wq <- grid_preds |> 
  summarise("Median_oxy" = hutils::weighted_quantile(v = oxy, w = est, p = 0.5),
            "10_oxy" = hutils::weighted_quantile(v = oxy, w = est, p = 0.1),
            "25_oxy" = hutils::weighted_quantile(v = oxy, w = est, p = 0.25),
            "75_oxy" = hutils::weighted_quantile(v = oxy, w = est, p = 0.75),
            "90_oxy" = hutils::weighted_quantile(v = oxy, w = est, p = 0.9),
            "Env_oxy" = median(oxy),
            
            "Median_temp" = hutils::weighted_quantile(v = temp, w = est, p = 0.5),
            "10_temp" = hutils::weighted_quantile(v = temp, w = est, p = 0.1),
            "25_temp" = hutils::weighted_quantile(v = temp, w = est, p = 0.25),
            "75_temp" = hutils::weighted_quantile(v = temp, w = est, p = 0.75),
            "90_temp" = hutils::weighted_quantile(v = temp, w = est, p = 0.9),
            "Env_temp" = median(temp),
            
            "Median_sal" = hutils::weighted_quantile(v = sal, w = est, p = 0.5),
            "10_sal" = hutils::weighted_quantile(v = sal, w = est, p = 0.1),
            "25_sal" = hutils::weighted_quantile(v = sal, w = est, p = 0.25),
            "75_sal" = hutils::weighted_quantile(v = sal, w = est, p = 0.75),
            "90_sal" = hutils::weighted_quantile(v = sal, w = est, p = 0.9),
            "Env_sal" = median(sal),
            
            .by = c(group2, quarter)) |> 
  separate(group2, into = c("species", "life_stage"), remove = FALSE)

wq_annual <- grid_preds |> 
  summarise("Median_oxy" = hutils::weighted_quantile(v = oxy, w = est, p = 0.5),
            "1st_oxy" = hutils::weighted_quantile(v = oxy, w = est, p = 0.25),
            "3rd_oxy" = hutils::weighted_quantile(v = oxy, w = est, p = 0.75),
            "Env_oxy" = median(oxy),
            
            "Median_temp" = hutils::weighted_quantile(v = temp, w = est, p = 0.5),
            "1st_temp" = hutils::weighted_quantile(v = temp, w = est, p = 0.25),
            "3rd_temp" = hutils::weighted_quantile(v = temp, w = est, p = 0.75),
            "Env_temp" = median(temp),
            
            "Median_sal" = hutils::weighted_quantile(v = sal, w = est, p = 0.5),
            "1st_sal" = hutils::weighted_quantile(v = sal, w = est, p = 0.25),
            "3rd_sal" = hutils::weighted_quantile(v = sal, w = est, p = 0.75),
            "Env_sal" = median(sal),
            
            .by = c(group2, year, quarter)) |> 
  separate(group2, into = c("species", "life_stage"), remove = FALSE)
```

## Plot conditional effects

```{r}
#| warning: false
#| message: false

p1 <- ggplot(preds, aes(temp, oxy, fill = est_sc)) + 
  facet_grid(life_stage~species) +
  geom_raster(alpha = 0.95) +
  geom_contour(aes(temp, oxy, z = est_sc), color = "grey95", bins = 10, linewidth = 0.3, alpha = 0.5, inherit.aes = FALSE) +
  geom_point(data = wq, aes(Median_temp, Median_oxy, color = as.factor(quarter)), inherit.aes = FALSE) +
  geom_errorbar(data = wq, aes(Median_temp, Median_oxy, xmin = `25_temp`, xmax = `75_temp`, color = as.factor(quarter)), inherit.aes = FALSE,
                alpha = 0.5) +
  geom_errorbar(data = wq, aes(Median_temp, Median_oxy, ymin = `25_oxy`, ymax = `75_oxy`, color = as.factor(quarter)), inherit.aes = FALSE,
                alpha = 0.5) +
  scale_fill_viridis() +
  scale_color_manual(values = c("grey90", "tomato3")) +
  labs(y = "Oxygen (ml/L)", 
       x = "Temperature (°C)",
       color = "Quarter",
       fill = expression("Scaled biomass density (kg/km"^2*")")) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5),
         fill = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(legend.position = "bottom",
        legend.key.width = unit(1.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.title.position = "top") +
  coord_cartesian(expand = 0) +
  NULL
  
tag_facet(p1, fontface = 1, col = "gray95", size = 3)

ggsave(paste0(home, "/figures/temp_oxy_conditional.pdf"), width = 18, height = 13, units = "cm")
```

```{r}
#| warning: false
#| message: false

# Oxygen
wi_median_oxy <- preds |>
  left_join(wq |>
              filter(quarter == 4) |>
              dplyr::select(group2, Median_oxy), by = "group2") |>
  distinct(group2, Median_oxy) |> 
  separate(group2, into = c("species", "life_stage"), remove = FALSE)

wi_median_temp <- preds |>
  left_join(wq |>
              filter(quarter == 4) |>
              dplyr::select(group2, Median_temp), by = "group2") |>
  distinct(group2, Median_temp) |> 
  separate(group2, into = c("species", "life_stage"), remove = FALSE)

ggplot() +
  facet_grid2(life_stage~species, independent = "y", scales = "free_y") +
  geom_vline(data = wi_median_oxy, aes(xintercept = Median_oxy), 
             linetype = 2, alpha = 0.5, linewidth = 0.4) +
  geom_line(data = preds, aes(oxy, est, color = temp, group = temp)) +
  scale_color_viridis(option = "plasma") +
  labs(x = "Oxygen (ml/L)",
       y = expression(paste("Log biomass density (kg/km"^2, ")")),
       color = "Temperature (°C)") +
  guides(color = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(legend.position = "bottom",
        legend.key.width = unit(1.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.title.position = "top") +
  coord_cartesian(expand = 0)

ggsave(paste0(home, "/figures/supp/oxy_conditional.pdf"), width = 19, height = 10, units = "cm")

# Temperature
ggplot() +
  facet_grid2(life_stage~species, independent = "y", scales = "free_y") +
  geom_vline(data = wi_median_temp, aes(xintercept = Median_temp), 
             linetype = 2, alpha = 0.5, linewidth = 0.4) +
  geom_line(data = preds, aes(temp, est, color = oxy, group = oxy)) +
  labs(x = "Temperature (°C)",
       y = expression(paste("Log biomass density (kg/km"^2, ")")),
       color = "Oxygen (ml/L)") +
  guides(color = guide_colorbar(title.position = "top", title.hjust = 0.5)) +
  theme(legend.position = "bottom",
        legend.key.width = unit(1.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.title.position = "top") +
  coord_cartesian(expand = 0)

ggsave(paste0(home, "/figures/supp/temp_conditional.pdf"), width = 19, height = 10, units = "cm")
```

## Plot weighted quantiles over time

```{r}
#| warning: false
#| message: false

t <- wq_annual |>
  pivot_longer(c("Median_oxy", `1st_oxy`, `3rd_oxy`, "Env_oxy",
                 "Median_temp", `1st_temp`, `3rd_temp`, "Env_temp",
                 "Median_sal", `1st_sal`, `3rd_sal`, "Env_sal")) |>
  mutate(var = ifelse(grepl("oxy", name), "Oxygen", NA),
         var = ifelse(grepl("sal", name), "Salinity", var),
         var = ifelse(grepl("temp", name), "Temperature", var),
         type = ifelse(grepl("Env", name), "Environment", "Biomass-weighted")) |> 
  filter(name %in% c("Median_oxy", "Median_temp", "Median_sal", "Env_oxy", "Env_temp", "Env_sal"))
   
t_env <- t |>
  filter(type == "Environment" & group2 == "Cod Adult") |>
  mutate(group2 = "Environment")
 
# Plot the slopes over time for group and quarter, compare to the environment slope.
s_slopes <- t |> filter(!type == "Environment") |>
  mutate(id = paste(group2, var, quarter, sep = "_")) |> 
  ungroup() |> 
  dplyr::select(year, id, value)

t_slopes <- t_env |>
  mutate(id = paste(group2, var, quarter, sep = "_")) |> 
  dplyr::select(year, id, value)

slopes <- bind_rows(s_slopes, t_slopes)

# Calculate slopes over time
slopes2 <- slopes %>%
  split(.$id) |>
  purrr::map(~lm(value ~ year, data = .x)) |>
  purrr::map_df(broom::tidy, .id = 'Year') |>
  filter(term == "year") |> 
  mutate(upr = estimate + 1.96*std.error,
         lwr = estimate - 1.96*std.error,
         sig = ifelse(estimate > lwr & estimate < upr, "sig.", "not sig.")) |> 
  rename(id = Year, 
         year_slope = estimate) |> 
  dplyr::select(id, year_slope, sig, lwr, upr) |> 
  separate(id, sep = "_", into = c("group2", "variable", "quarter"), remove = FALSE) |> 
  mutate(quarter2 = ifelse(quarter == 1, "Quarter 1", "Quarter 4"))
  
vlines <- slopes2 |> 
  filter(group2 == "Environment")

order <- c("Cod Adult", "Cod Juvenile", "Flounder Adult", "Flounder Juvenile",
           "Plaice Adult", "Plaice Juvenile")

slopes2$group2 <- factor(slopes2$group2, levels = order)

p1 <- slopes2 |> 
  filter(!group2 == "Environment") |> 
  ggplot(aes(year_slope*10, group2, xmin = lwr*10, xmax = upr*10, color = group2)) + 
  geom_rect(data = vlines, aes(ymin = -Inf, ymax = Inf, xmin = lwr*10, xmax = upr*10, fill = "95% C.I. Environmental slope"),
            inherit.aes = FALSE, alpha = 0.1) +
  geom_vline(xintercept = 0, linetype = 3, color = "tomato2", alpha = 1) +
  geom_vline(data = vlines, aes(xintercept = year_slope*10, linetype = "Environmental slope"), alpha = 0.7) +
  geom_point(size = 2, position = position_dodge(width = 0.4)) + 
  geom_errorbar(position = position_dodge(width = 0.4), width = 0) +
  facet_grid2(quarter2 ~ variable, scales = "free_x") +
  scale_fill_manual(values = "grey10") +
  scale_linetype_manual(values = 2) +
  scale_color_brewer(palette = "Paired") +
  labs(color = "", x = "Change in variable per decade", linetype = "", fill = "", y = "") +
  theme(legend.position = "bottom",
        strip.text.x.top = element_text(margin = margin(b = 2))) +
  guides(color = "none") +
  NULL

tag_facet(p1, fontface = 1, col = "gray30", size = 3)

ggsave(paste0(home, "/figures/decadal_slopes.pdf"), width = 18, height = 11, units = "cm")
```

## Effective area occupied

```{r}
#| warning: false
#| message: false

# Trends in index and area occupied
# https://sdmtmb.github.io/sdmTMB/articles/poisson-link.html inverse link of est1 to get 
grid_preds$encounter <- 1 - exp(-exp(grid_preds$est1))

n_cell <- grid_preds |> 
  filter(group == "cod_juvenile" & year == max(year)) |> 
  filter(quarter == 4) |> 
  summarise(n = n()) |> pull(n)

encounter_sum <- grid_preds |> 
  filter(quarter == 4) |> 
  filter(encounter > 0.9) |> 
  summarise(n = n(),
            .by = c(year, group2)) |> 
  mutate(prop = n / n_cell) |> 
  separate(group2, into = c("species", "life_stage"), remove = FALSE)

hist(encounter_sum$prop)

# Create a function to get colors from the actual scale
get_gradient_colors <- function(values, midpoint = 1) {
  scales::div_gradient_pal(
    low = scales::muted("red"),
    mid = "white", 
    high = scales::muted("blue"),
    space = "Lab"
  )(scales::rescale(values, from = c(0, midpoint * 2)))
}

legend_colors <- get_gradient_colors(c(0.5, 1, 2), midpoint = 1)

p1 <- encounter_sum |> 
  left_join(index |> dplyr::select(year, est, group2)) |> 
  mutate(prop_ct = prop / mean(prop, na.rm = TRUE), .by = group2) |> 
  ggplot(aes(year, est/1000000, fill = prop_ct, size = prop_ct)) + 
  facet_grid2(life_stage~species, scales = "free", independent = "y") + 
  geom_point(alpha = 0.75, shape = 21, color = "gray30") + 
  geom_smooth(aes(year, est/1000000), inherit.aes = FALSE, color = "gray40", 
              linewidth = 0.5, method = "gam", formula = y~s(x, k = 5), se = FALSE) + 
  scale_size_continuous(breaks = c(0.5, 1, 2), range = c(0.5, 3)) + 
  labs(y = "Biomass index (1000 tonnes)", size = "Area occupied", x = "Year") + 
  scale_fill_gradient2(midpoint = 1, low = scales::muted("red"), 
                       mid = "white", high = scales::muted("blue")) + 
  guides(fill = "none", 
         size = guide_legend(title.hjust = 0.5, title.position = "top",
                             override.aes = list(fill = legend_colors))) + 
  theme(legend.position = "bottom",
        legend.key.width = unit(1.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.title.position = "top")

tag_facet(p1, fontface = 1, col = "gray30", size = 3)

ggsave(paste0(home, "/figures/area_index.pdf"), width = 18, height = 11, units = "cm")

p2 <- encounter_sum |>
  left_join(index |> dplyr::select(year, est, group2)) |>
  mutate(prop_ct = prop / mean(prop, na.rm = TRUE), .by = group2) |>
  ggplot(aes(year, prop_ct, fill = est/1000000, size = est/1000000)) +
  facet_grid2(life_stage~species, scales = "free", independent = "y") +
  geom_point(alpha = 0.75, shape = 21, color = "gray30") +
  geom_smooth(aes(year, prop_ct), inherit.aes = FALSE, color = "gray40",
              linewidth = 0.5, method = "gam", formula = y~s(x, k = 5), se = FALSE) +
  scale_size_continuous(breaks = c(0.5, 1, 2), range = c(0.5, 3)) +
  labs(size = "Biomass index (1000 tonnes)", y = "Area occupied", x = "Year") +
  scale_fill_gradient2(midpoint = 1, low = scales::muted("red"),
                       mid = "white", high = scales::muted("blue")) +
  guides(fill = "none",
         size = guide_legend(title.hjust = 0.5, title.position = "top",
                             override.aes = list(fill = legend_colors))) +
  theme(legend.position = "bottom",
        legend.key.width = unit(1.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.title.position = "top")

p2 <- tag_facet(p2, fontface = 1, col = "gray30", size = 3)

ggsave(paste0(home, "/figures/supp/area_index_supp.pdf"), width = 18, height = 11, units = "cm")
  
# Correlation between area and index
cor_dat <- index |>
  left_join(encounter_sum)

cor_dat |>
  ggplot(aes(log(est/1000000), prop, color = group2, fill = group2)) +
  labs(x = "log(biomass index, 1000 tonnes)",
       y = "Area occupied (fraction of cells with >90% prob. occur.)",
       size = "Scaled mean biomass density",
       color = "", fill = "") +
  geom_point(size = 2.5, alpha = 0.6) +
  geom_smooth(aes(log(est/1000000), prop, color = group2), inherit.aes = FALSE,
              method = "gam", formula = y~s(x, k = 5), se = FALSE) +
  scale_color_brewer(palette = "Paired") +
  scale_fill_manual(
    values = scales::alpha(
      RColorBrewer::brewer.pal(length(unique(cor_dat$group2)), "Paired"),
      0.3
      )
  ) +
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title.position = "top"),
         alpha = "none")

ggsave(paste0(home, "/figures/ind_area_corr.pdf"), width = 18, height = 15, units = "cm")
```

```{r}
knitr::knit_exit()
```

```{r}
# EAO captures both range size AND within-range density patterns. It's a composite metric.
# If EAO goes up: Index growing faster than mean density, OR Mean density declining faster than index
# Interpretation: Population spread over larger effective area (could be range expansion OR spreading thin)
# 
# If EAO goes down: Mean density growing faster than index, OR Index declining faster than mean density
# Interpretation: Population in smaller effective area (could be range contraction OR concentrating)
# 
# EAO stable: Effective spatial footprint unchanged. Abundance changes are proportional to density changes
#
# EAO: If I redistributed all the individuals uniformly, how much area would they cover at the observed mean density?
#
# Maybe its better to just show two trends: # cells above X and index (2 plots color by group)

# EAO
# eaos |> 
#   mutate(est_sc = est / mean(est), .by = group2) |> 
#   mutate(group3 = ifelse(group2 %in% c("Cod Adult", "Flounder Juvenile", "Dab All"), 1, 2)) |> 
#   ggplot(aes(year, est_sc, color = group2)) +
#   geom_point() +
#   facet_wrap(~group3, scales = "free") +
#   labs(y = "EAO", x = "Year") +
#   theme(legend.position = "bottom",
#         legend.title = element_blank()) +
#   scale_color_brewer(palette = "Paired") +
#   #facet_wrap(~group2, scales = "free") +
#   geom_smooth(method = "gam", formula = y~s(x, k=3), se = FALSE)
```

```{r}
# Calculate cumulative biomass density to get core distribution area by species
# grid_preds_c <- grid_preds |> filter(quarter == 4)
# 
# list_cumsum <- list()
# 
# for(i in unique(grid_preds_c$group2)) {
# 
#   list_cumsum[[i]] <- grid_preds_c |>
#     filter(group2 == i) |>
#     mutate(id = paste(X, Y, group2, sep = "_")) |>
#     summarise(grid_mean = median(exp(est1 + est2)), .by = id) |> # note the delta_gamma poisson link!
#     arrange(desc(grid_mean)) |>
#     mutate(cumsum = cumsum(grid_mean),
#            sum = sum(grid_mean),
#            perc = cumsum / sum,
#            # rather arbitrary percentile but still
#            cumulative = ifelse(perc < 0.99, "Y", "N")) |>
#     dplyr::select(id, cumulative, grid_mean, cumsum, sum, perc)
# 
# }
# 
# d_cumulative <- bind_rows(list_cumsum)

mean_dens <- grid_preds_c |>
  mutate(id = paste(X, Y, group2, sep = "_")) |>
  left_join(d_cumulative, by = "id") |> 
  filter(cumulative == "Y") |> 
  summarise(mean_dens = mean(est1 + est2),
            .by = c(year, group2)) |>
  mutate(mean_dens_sc = mean_dens/mean(mean_dens), .by = group2)

cor_dat <- index |>
  left_join(encounter_sum) #|>
  #left_join(mean_dens)

cor_dat |>
  ggplot(aes(log(est/1000000), prop, color = group2, fill = group2)) +
  labs(x = "log(biomass index)",
       y = "Area occupied (fraction of cells with >90% prob. occur.)",
       size = "Scaled mean biomass density",
       color = "", fill = "") +
  geom_point(size = 2.5, alpha = 0.6) +
  geom_smooth(aes(log(est/1000000), prop, color = group2), inherit.aes = FALSE,
              method = "gam", formula = y~s(x, k = 5), se = FALSE) +
  scale_color_brewer(palette = "Paired") +
  scale_fill_manual(
    values = scales::alpha(
      RColorBrewer::brewer.pal(length(unique(cor_dat$group2)), "Paired"),
      0.3
      )
  ) +
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title.position = "top"),
         alpha = "none")

ggsave(paste0(home, "/figures/ind_area_corr.pdf"), width = 17, height = 14, units = "cm")


p1 <- cor_dat |>
  ggplot(aes(log_est, prop, size = mean_dens_sc, color = group2, fill = group2)) +
  labs(x = "log(biomass index, kg)",
       y = "Area occupied",
       size = "Scaled mean biomass density",
       color = "", fill = "") +
  geom_point(shape = 21) +
  scale_size_continuous(range = c(0.1, 5)) +
  geom_smooth(aes(log_est, prop, color = group2), inherit.aes = FALSE,
              method = "gam", formula = y~s(x, k = 5), se = FALSE) +
  scale_color_brewer(palette = "Paired") +
    scale_fill_manual(
    values = scales::alpha(
      RColorBrewer::brewer.pal(length(unique(cor_dat$group2)), "Paired"),
      0.3
      )
  ) +
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title.position = "top"),
         alpha = "none") +
  annotate("text", label = "(a)", x = -Inf, y = Inf, vjust = 1.5, hjust = -0.9, color = "gray40", size = 3)

p1

ggsave(paste0(home, "/figures/dens_area_corr.pdf"), width = 18, height = 22, units = "cm")


# p2 <- cor_dat |>
#   ggplot(aes(prop, mean_dens_sc, size = log_est, color = group2, fill = group2)) +
#   labs(x = "Area occupied",
#        y = "Scaled mean biomass density",
#        size = "log(biomass index, kg)",
#        color = "", fill = ""
#     ) +
#   geom_point(shape = 21) +
#   scale_size_continuous(range = c(0.1, 5)) +
#   geom_smooth(aes(prop, mean_dens_sc, color = group2), inherit.aes = FALSE,
#               method = "gam", formula = y~s(x, k = 5), se = FALSE) +
#   scale_color_brewer(palette = "Paired") +
#     scale_fill_manual(
#     values = scales::alpha(
#       RColorBrewer::brewer.pal(length(unique(cor_dat$group2)), "Paired"),
#       0.3
#       )
#   ) +
#   theme(legend.position = "bottom") +
#   guides(size = guide_legend(title.position = "top"),
#          alpha = "none") +
#   annotate("text", label = "(b)", x = -Inf, y = Inf, vjust = 1.5, hjust = -0.9, color = "gray40", size = 3)
# 
# p3 <- cor_dat |>
#   ggplot(aes(log_est, mean_dens_sc, size = prop, color = group2, fill = group2)) +
#   labs(size = "Area occupied",
#        y = "Scaled mean biomass density",
#        x = "log(biomass index, kg)",
#        color = "", fill = ""
#     ) +
#   geom_point(shape = 21) +
#   scale_size_continuous(range = c(0.1, 5)) +
#   # geom_smooth(aes(log_est, mean_dens_sc, color = group2), inherit.aes = FALSE,
#   #             method = "gam", formula = y~s(x, k = 5), se = FALSE) +
#   scale_color_brewer(palette = "Paired") +
#     scale_fill_manual(
#     values = scales::alpha(
#       RColorBrewer::brewer.pal(length(unique(cor_dat$group2)), "Paired"),
#       0.3
#       )
#   ) +
#   theme(legend.position = "bottom") +
#   guides(size = guide_legend(title.position = "top"),
#          alpha = "none") +
#   annotate("text", label = "(b)", x = -Inf, y = Inf, vjust = 1.5, hjust = -0.9, color = "gray40", size = 3)
# 
# (p1 / p2 / p3) +
#   plot_layout(guides = "collect") &
#   theme(#legend.position = "bottom",
#         legend.direction = "vertical")
# 
# ggsave(paste0(home, "/figures/dens_area_corr.pdf"), width = 18, height = 22, units = "cm")
# 
# # Heat map?
# cor_dat |> as.data.frame()
# 
# # Calculate slopes for each group2 and variable
# slopes <- cor_dat |>
#   mutate(
#     prop_sc = scale(prop)[,1],
#     mean_dens_sc = scale(mean_dens)[,1],
#     log_est_sc = scale(log_est)[,1],
#     year_sc = scale(year)[,1],
#     .by = group2
#   ) |>
#   summarise(
#     slope_prop = coef(lm(prop_sc ~ year_sc))[2],
#     slope_mean_dens = coef(lm(mean_dens_sc ~ year_sc))[2],
#     slope_log_est = coef(lm(log_est_sc ~ year_sc))[2],
#     .by = group2
#   ) |>
#   pivot_longer(
#     cols = starts_with("slope_"),
#     names_to = "variable",
#     values_to = "slope",
#     names_prefix = "slope_"
#   )
# 
# # Create geom_tile plot
# ggplot(slopes, aes(variable, group2, fill = slope)) +
#   geom_tile(color = "white", linewidth = 0.5) +
#   scale_fill_gradient2(midpoint = 0) +
#   coord_cartesian(expand = 0) +
#   theme(axis.title = element_blank(),
#         )
# 
# ggsave(paste0(home, "/figures/heatmatp.pdf"), width = 11, height = 8, units = "cm")



# encounter_sum |>
#   ggplot(aes(year, prop, color = group2)) +
#   geom_point(size = 2, alpha = 0.5) +
#   geom_smooth(method = "gam", formula = y~s(x, k = 5), se = FALSE) +
#   labs(x = "Year",
#        y = "Area occupied") +
#   theme(legend.position = "bottom",
#         legend.title = element_blank()) +
#   scale_color_brewer(palette = "Paired") +
#   annotate("text", label = "(b)", x = -Inf, y = Inf, vjust = 1.5, hjust = -0.9, color = "gray40", size = 3) +
#   guides(color = "none")
# 
# ggsave(paste0(home, "/figures/supp/area_over_time.pdf"), width = 18, height = 20, units = "cm")
```

```{r}
# test plts
# 
# head(cor_dat)
# 
# ind <- cor_dat |> 
#   dplyr::select(est, year, group2) |> 
#   rename(index = est)
# 
# eao <- eaos |> 
#   dplyr::select(est, year, group2) |> 
#   rename(eao = est)
# 
# tt <- left_join(ind, eao, by = c("group2", "year"))
# 
# ggplot(tt, aes(index, eao, color = group2)) + 
#   facet_wrap(~group2, scales = "free") +
#   geom_point() + 
#   geom_smooth(method = "lm", se = FALSE)
```


## Map plots

```{r}
# Calculate cumulative biomass density to get core distribution area by species
trends <- grid_preds

list_cumsum <- list()

for(i in unique(trends$group2)) {

  list_cumsum[[i]] <- trends |>
    filter(group2 == i) |>
    mutate(id = paste(X, Y, group2, sep = "_")) |>
    summarise(grid_mean = median(exp(est1 + est2)), .by = id) |> # note the delta_gamma poisson link!
    arrange(desc(grid_mean)) |>
    mutate(cumsum = cumsum(grid_mean),
           sum = sum(grid_mean),
           perc = cumsum / sum,
           # rather arbitrary percentile but still
           cumulative = ifelse(perc < 0.99, "Y", "N")) |>
    dplyr::select(id, cumulative, grid_mean, cumsum, sum, perc)

}

d_cumulative <- bind_rows(list_cumsum)


# Because we trim the grids, let's add a polygon that is the overall outside border.
border_df <- grid_preds |>
  filter(year == 2000)

z <- concaveman(cbind(border_df$X, border_df$Y), concavity = 1)
#plot(z)
z_poly <- sp::SpatialPolygons(list(sp::Polygons(list(sp::Polygon(z)), ID = 1)))
domain <- as.data.frame(z_poly@polygons[[1]]@Polygons[[1]]@coords)
colnames(domain) <- c("X", "Y")

dd <- grid_preds |>
  filter(year %in% c(1994, 2001, 2008, 2015, 2022)) |>
  mutate(mean_est = mean(est), .by = c(X, Y, group2)) |>
  mutate(est_ct = est/max(est),
         est_diff = est / mean_est,
         .by = group2) |>
  mutate(id = paste(X, Y, group2, sep = "_")) |>
  left_join(d_cumulative) |>
  mutate(est_diff = ifelse(cumulative == "N", NA, est_diff))

plot_map_fc +
  geom_raster(data = dd, aes(X*1000, Y*1000, fill = est_diff)) +
  facet_grid(group2 ~ year) +
  geom_path(data = domain, aes(X*1000, Y*1000), color = "red", linewidth = 0.2, linetype = 2) +
  scale_fill_gradient2(midpoint = 1, na.value="grey94") +
  labs(fill = "Biomass density relative to mean") +
  theme(axis.text.x = element_text(angle = 90)) +
  NULL

ggsave(paste0(home, "/figures/map_trends.pdf"), width = 18, height = 22, units = "cm")


# trends <- trends |> 
#   mutate(id = paste(X, Y, group2, sep = "_")) |> 
#   left_join(d_cumulative, by = "id")
# 
# # Plot core habitat on map by group
# plot_map + 
#   geom_raster(data = trends, aes(X*1000, Y*1000, fill = cumulative)) +
#   facet_wrap(~group2)
# 
# 
# # Calculate slopes
# est_yr_slopes <- trends |>
#   filter(cumulative == "Y") |> 
#   mutate(id = paste(X, Y, group2, sep = "_"),
#          decade = year/10) %>%
#   split(.$id) |>
#   purrr::map(~lm(est ~ decade, data = .x)) |>
#   purrr::map_df(broom::tidy, .id = 'id') |>
#   filter(term == 'decade') |> 
#   dplyr::select(id, estimate) |> 
#   rename(temp_slope = estimate)
# 
# tt <- est_yr_slopes |> 
#   left_join(trends |> 
#               filter(cumulative == "Y") |> 
#               dplyr::select(X, Y, group2, id),
#             by = "id")
# 
# tt <- tt |> 
#   mutate(temp_slope_ct = temp_slope / mean(temp_slope), .by = group2) |> 
#   filter(temp_slope > quantile(temp_slope_ct, 0.01) & temp_slope < quantile(temp_slope, 0.99),
#          .by = group2) 
# 
# plot_map + 
#   geom_raster(data = tt, aes(X*1000, Y*1000, fill = temp_slope)) +
#   facet_wrap(~group2) +
#   scale_fill_gradient2(midpoint = 0) +
#   NULL
# 
# ggplot() + 
#   geom_raster(data = tt, aes(X*1000, Y*1000, fill = temp_slope)) +
#   facet_wrap(~group2, scales = "free") +
#   scale_fill_gradient2(midpoint = 1) +
#   NULL
```

