---
title: "Calculate metabolic index trends for each species"
author: "Max Lindmark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 12,
  fig.asp = 0.618,
  fig.align ='center'
)
```

# Intro
Main analysis: This scripts reads prediction grids with predicted biomass densities ("02_fit_sdm_pred") and calculates metabolic indexes by species and life stage, as well as temporal trends of the metabolic index, temperature and oxygen.

```{r load libraries, message=FALSE, warning=TRUE}
# Load libraries, install if needed
library(tidyverse)
library(tidylog)
library(RCurl)
library(devtools)
library(sdmTMB)
library(rMR)
library(patchwork)
library(raster)
library(VoCC)
library(RColorBrewer)
library(viridis)

# Source code for plots
source_url("https://raw.githubusercontent.com/maxlindmark/spatial-metabolic-index/main/R/functions/map-plot.R")

theme_set(theme_plot())

pal <- brewer.pal(name = "Dark2", n = 8)
```

```{r}
# Read predictions grids
d <- read_csv("output/grid_pred_biomass_02.csv") %>%
  separate(model, c("species", "life_stage"), sep = "_", remove = FALSE) %>%
  rename(group = model)

# Spatial trend model instead
# d <- read_csv("output/spatial_trend_biom_pred.csv") %>% 
#   separate(group, c("species", "life_stage"), sep = "_", remove = FALSE)

# Read metabolic parameter estimates and left_join
mi_pars <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/spatial-metabolic-index/main/data/clean/mi_params.csv") %>% 
  dplyr::select(-...1, -temp)

# TODO: for now we'll use plaice parameters for flounder, see "00_estimate_mi_params.Rmd"
mi_pars2 <- mi_pars
mi_pars2[4, c(4:5)] <- mi_pars2[1, c(4:5)]

d <- left_join(d, mi_pars2, by = "species")

# Read size csv to calculate the metabolic index
sizes <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/spatial-metabolic-index/main/data/clean/sizes.csv") %>% 
  mutate(group = paste(species, name, sep = "_")) %>% 
  dplyr::select(group, B)

d <- left_join(d, sizes, by = "group")
```

## Calculate the metabolic index

```{r calculate metabolic index}
# Before we can calculate the pressure based metabolic index, we'll need to convert oxygen from ml/L mg/L and partial pressure
# Some conversions
# oxygen: https://www.ices.dk/data/tools/Pages/Unit-conversions.aspx
# pressure: https://bluerobotics.com/learn/pressure-depth-calculator/
# First calculate pressure in pascal: p_tot = (r*g*h) + p_atm, then to kgPa and finally atm
rho = 1030 # density of water
p_atm = 1.01325 # atmospheric pressure
g = 9.807 # gravity of earth

# Convert to partial pressure oxygen from ml/L
d$po2 <- DO.unit.convert(d$oxy*(1/0.7), # d$oxy is in unit ml/L so we first need to convert to mg/L
                         DO.units.in = "mg/L", 
                         DO.units.out = "PP", 
                         bar.press = ((rho*g*d$depth + p_atm)*10^-5)*0.986923, 
                         bar.units.in = "atm",
                         bar.units.out = "kpa",
                         temp.C = d$temp,
                         salinity = 10, # TODO: d$sal, # let's fix salinity for easier comparison. It has a minor effect in this range
                         salinity.units = "pp.thou")

# Oxygen is ml/L, We want micro mol/L. 1 ml/l = 10^3/22.391 = 44.661 micro mol/l
d$oxy_si <- (d$oxy * (10^3)) / 22.391

# Calculate metabolic indices for a given mass and the temperature and oxygen in data
# Line 123 in https://github.com/fate-spatialindicators/SDM_O2/blob/master/code/mi_functions.R
kb <- 0.000086173324 # Boltzmann's constant
t_ref <- 15 # arbitrary reference temperature

# Calculate the metabolic index for concentration 
d <- d %>%
  mutate(inv_temp = (1/(temp + 273.15) - 1/(t_ref + 273.15)),
         phi_c = A0_o2*(B^n_o2)*oxy_si * exp((E_o2/kb)*inv_temp))
```

## Trim the prediction grid by species cumulative biomass

```{r}
# Cumulative filter
# d_test <- data.frame(y = round(rnorm(10, 10, 2))) %>% 
#   arrange(desc(y)) %>%
#   mutate(cumsum = cumsum(y),
#          sum = sum(y),
#          perc = cumsum / sum)
# 
# d_test
# 
# d_test %>% filter(perc < 0.95)

d_grid_keep <- d %>% 
  mutate(group = paste(group, quarter, sep = "_")) %>% 
  group_by(X, Y, group) %>% 
  summarise(grid_mean = mean(exp(est))) %>% 
  ungroup() %>% 
  group_by(group) %>%
  arrange(desc(grid_mean)) %>% 
  mutate(cumsum = cumsum(grid_mean),
         sum = sum(grid_mean),
         perc = cumsum / sum) %>% 
  ungroup() %>% 
  filter(perc < 0.95) %>% 
  mutate(id = paste(X, Y, group, sep = "_"))

# Filter the main dataset to include these grid cells only
pred_grid_trim <- d %>% 
  mutate(group = paste(group, quarter, sep = "_")) %>% 
  mutate(id = paste(X, Y, group, sep = "_")) %>% 
  filter(id %in% unique(d_grid_keep$id))

# ... Now that we have the final set of grid cells by species, summarize grid cell average oxygen, temperature, phi and biomass
pred_grid_sum <- pred_grid_trim %>% 
  group_by(id) %>% 
  summarise(mean_log_biomass = mean(est),
            mean_temp = mean(temp),
            mean_oxy = mean(oxy),
            mean_phi = mean(phi_c)) %>% 
  # Center the average across year variables
  mutate(mean_log_biomass_ct = mean_log_biomass - mean(mean_log_biomass),
         mean_temp_ct = mean_temp - mean(mean_temp),
         mean_oxy_ct = mean_oxy - mean(mean_oxy),
         mean_phi_ct = mean_phi - mean(mean_phi)) %>%
  ungroup() %>% 
  dplyr::select(id, mean_log_biomass, mean_temp, mean_oxy, mean_phi,
                mean_log_biomass_ct, mean_temp_ct, mean_oxy_ct, mean_phi_ct)

# Calculate trends over time for biomass, temperature and phi
# This is if I use a spatial trend model
# biom_yr_slopes <- pred_grid_trim %>%
#   mutate(biom_slope = scaled_year + zeta_s_scaled_year) %>% 
#   dplyr::select(X, Y, species, life_stage, quarter, biom_slope) %>% 
#   mutate(X = as.numeric(X),
#          Y = as.numeric(Y),
#          quarter = as.character(quarter))

biom_yr_slopes <- pred_grid_trim %>%
  mutate(id = paste(X, Y, group, sep = "_")) %>%
  split(.$id) %>%
  purrr::map(~lm(exp(est) ~ year, data = .x)) %>%
  purrr::map_df(broom::tidy, .id = 'id') %>%
  filter(term == 'year') %>%
  dplyr::select(id, estimate) %>%
  rename(biom_slope = estimate) %>%
  separate(id, sep = "_", into = c("X", "Y", "species", "life_stage", "quarter")) %>%
  mutate(X = as.numeric(X),
         Y = as.numeric(Y))

temp_yr_slopes <- pred_grid_trim %>%
  mutate(id = paste(X, Y, group, sep = "_")) %>%
  split(.$id) %>%
  purrr::map(~lm(temp ~ year, data = .x)) %>%
  purrr::map_df(broom::tidy, .id = 'id') %>%
  filter(term == 'year') %>% 
  dplyr::select(id, estimate) %>% 
  rename(temp_slope = estimate) %>% 
  separate(id, sep = "_", into = c("X", "Y", "species", "life_stage", "quarter")) %>% 
  mutate(X = as.numeric(X),
         Y = as.numeric(Y))

phi_yr_slopes <- pred_grid_trim %>%
  mutate(id = paste(X, Y, group, sep = "_")) %>%
  split(.$id) %>%
  purrr::map(~lm(phi_c ~ year, data = .x)) %>%
  purrr::map_df(broom::tidy, .id = 'id') %>%
  filter(term == 'year') %>%
  dplyr::select(id, estimate) %>% 
  rename(phi_slope = estimate) %>% 
  separate(id, sep = "_", into = c("X", "Y", "species", "life_stage", "quarter")) %>% 
  mutate(X = as.numeric(X),
         Y = as.numeric(Y))

# Join these data!
trends <- left_join(temp_yr_slopes, biom_yr_slopes, by = c("X", "Y", "species", "life_stage", "quarter")) %>% 
  left_join(phi_yr_slopes, by = c("X", "Y", "species", "life_stage", "quarter"))

ggplot(trends, aes(temp_slope, biom_slope)) + 
  geom_point(alpha = 0.5) + 
  facet_wrap(life_stage ~ species, scales = "free") + 
  stat_smooth(method = "lm")

ggplot(trends, aes(phi_slope, biom_slope)) + 
  geom_point(alpha = 0.5) + 
  facet_wrap(life_stage ~ species, scales = "free") + 
  stat_smooth(method = "lm")

# Now join in the average variables to the trends data
trends <- trends %>% 
  mutate(id = paste(X, Y, species, life_stage, quarter, sep = "_")) %>% 
  left_join(pred_grid_sum, by = "id")
```

```{r}
# Save data
write_csv(trends, "data/clean/trends.csv")
```
