---
title: "Plot trends and velocities"
author: "Max Lindmark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    embed-resources: true
    fig-width: 8
    #fig-asp: 0.618
knitr: 
  opts_chunk:
    fig.align: center
editor: source
execute: 
  echo: true
  eval: true
  cache: false
---

## Intro

This scripts reads prediction grids with predicted biomass densities ("02_fit_sdm_pred") and calculates metabolic indexes by species and life stage, as well as velocities of temperature and oxygen.

## Load packages & source functions

```{r load libraries}
#| message: false
#| warning: false

# Load libraries, install if needed
pkgs <- c("tidyverse", "tidylog", "RCurl", "devtools", "patchwork",
          "viridis", "RColorBrewer", "here", "raster", "concaveman") 

if(length(setdiff(pkgs,rownames(installed.packages()))) > 0){

    install.packages(setdiff(pkgs, rownames(installed.packages())), dependencies = T)
  
  }

invisible(lapply(pkgs, library, character.only = T))

# Set path
home <- here::here()

# Source code for map plots
# For some reason I can't source it directly from github...
# You need: # devtools::install_github("seananderson/ggsidekick") # not on CRAN; library(ggsidekick)
# devtools::source_url("https://raw.githubusercontent.com/maxlindmark/pred-prey-overlap/main/R/functions/map-plot.R")
source(paste0(home, "/R/functions/map-plot.R"))
options(ggplot2.continuous.colour = "viridis")
```

## Read trends & velocities and plot!

```{r}
velo <- read_csv(paste0(home, "/data/clean/velocities.csv"))
trends <- read_csv(paste0(home, "/data/clean/trends.csv"))
```

## Plot environmental variables!

```{r}
velo2 <- velo |> filter(group == "Plaice_Adult" & quarter == 4)
trends2 <- trends |> filter(group == "Plaice_Adult" & quarter == 4)

# First row, temperature
p1 <- plot_map_fc + 
  geom_raster(data = velo2, aes(X*1000, Y*1000, fill = mean_temp)) +
  scale_fill_viridis(option = "magma", name = "Mean °C") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Mean temperature")

p2 <- plot_map_fc + 
  geom_raster(data = trends2, aes(X*1000, Y*1000, fill = temp_slope)) +
  scale_fill_viridis(option = "rocket", name = "°C×decade<sup>-1</sup>") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Temperature trends")

p3 <- plot_map_fc + 
  geom_raster(data = velo2, aes(X*1000, Y*1000, fill = temp_vel)) +
  scale_fill_viridis(option = "plasma", name = "km×decade<sup>-1</sup>") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  geom_sf() +
  ggtitle("Temperature velocities")


# Second row, oxygen

p4 <- plot_map_fc + 
  geom_raster(data = velo2, aes(X*1000, Y*1000, fill = mean_oxy)) +
  scale_fill_viridis(option = "cividis", name = "Mean O<sub>2</sub>", direction = -1) +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.title.x = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6),
        plot.title = ggtext::element_markdown()) + 
  ggtitle("Mean O<sub>2</sub>")

p5 <- plot_map_fc + 
  geom_raster(data = trends2, aes(X*1000, Y*1000, fill = oxy_slope)) +
  scale_fill_viridis(option = "mako", name = "O<sub>2</sub>×decade<sup>-1</sup>") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6),
        plot.title = ggtext::element_markdown()) + 
  ggtitle("O<sub>2</sub> trends")


p6 <- plot_map_fc + 
  geom_raster(data = velo2, aes(X*1000, Y*1000, fill = oxy_vel)) +
  scale_fill_viridis(option = "plasma", name = "km×decade<sup>-1</sup>") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6),
        plot.title = ggtext::element_markdown()) + 
  ggtitle("O<sub>2</sub> velocities")


(p1 + p2 + p3) / (p4 + p5 + p6) + plot_annotation(tag_levels = "A")

ggsave(paste0(home, "/figures/env_vars_space.pdf"), width = 17, height = 11, units = "cm", device = cairo_pdf)
```

## Now do biotic variables... add here the boundary!

```{r}
# Because we trim the grids, let's add a polygon that is the overall outside border.
border_df <- velo
z <- concaveman(cbind(border_df$X, border_df$Y), concavity = 2)
plot(z)
z_poly <- sp::SpatialPolygons(list(sp::Polygons(list(sp::Polygon(z)), ID = 1)))
domain <- as.data.frame(z_poly@polygons[[1]]@Polygons[[1]]@coords)
colnames(domain) <- c("X", "Y")

ggplot(domain, aes(x = X, y = Y)) +
  geom_polygon(fill = NA, color = "tomato")

velo2 <- velo |> filter(quarter == 4 & life_stage == "Adult")
trends2 <- trends |> filter(quarter == 4 & life_stage == "Adult")

# First row!
p1 <- plot_map_fc + 
  geom_raster(data = velo2 |> filter(species == "Cod"), aes(X*1000, Y*1000, fill = mean_log_biomass)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) +
  scale_fill_viridis(option = "viridis", name = "log(kg×km<sup>-2</sup>)") +
  labs(y = "", x = "") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Mean cod biomass")

p2 <- plot_map_fc + 
  geom_raster(data = velo2 |> filter(species == "Flounder"), aes(X*1000, Y*1000, fill = mean_log_biomass)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) +
  scale_fill_viridis(option = "viridis", name = "log(kg×km<sup>-2</sup>)") +
  labs(y = "", x = "") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Mean flounder biomass")

p3 <- plot_map_fc + 
  geom_raster(data = velo2 |> filter(species == "Plaice"), aes(X*1000, Y*1000, fill = mean_log_biomass)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) +
  scale_fill_viridis(option = "viridis", name = "log(kg×km<sup>-2</sup>)") +
  labs(y = "", x = "") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Mean plaice biomass")

p1 + p2 + p3

# Second row! (trends)
p4 <- plot_map_fc + 
  geom_raster(data = trends2 |> filter(species == "Cod"), aes(X*1000, Y*1000, fill = biom_slope)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) +
  #scale_fill_viridis(option = "rocket", name = "Cod trends") +
  scale_fill_gradient2(name = "kg×km<sup>-2</sup>×decade<sup>-1</sup>") + 
  theme_sleek(base_size = 8) +
  labs(x = "") +
  theme(legend.position = c(0.24, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Cod biomass trends")

p5 <- plot_map_fc + 
  geom_raster(data = trends2 |> filter(species == "Flounder"), aes(X*1000, Y*1000, fill = biom_slope)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) + 
  #scale_fill_viridis(option = "cividis", name = "Flounder trends") +
  scale_fill_gradient2(name = "kg×km<sup>-2</sup>×decade<sup>-1</sup>") + 
  labs(y = "", x = "") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.24, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Flounder biomass trends")

p6 <- plot_map_fc + 
  geom_raster(data = trends2 |> filter(species == "Plaice"), aes(X*1000, Y*1000, fill = biom_slope)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) + 
  #scale_fill_viridis(option = "mako", name = "Plaice trends") +
  scale_fill_gradient2(name = "kg×km<sup>-2</sup>×decade<sup>-1</sup>") + 
  labs(y = "", x = "") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.24, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Plaice biomass trends")


# Third row! (velocities)
p7 <- plot_map_fc + 
  geom_raster(data = velo2 |> filter(species == "Cod"), aes(X*1000, Y*1000, fill = bio_vel)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) + 
  #scale_fill_viridis(option = "rocket", name = "Cod velocities") +
  scale_fill_gradient2(name = "km×decade<sup>-1</sup>") + 
  labs(y = "", x = "") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Cod velocities")

p8 <- plot_map_fc + 
  geom_raster(data = velo2 |> filter(species == "Flounder"), aes(X*1000, Y*1000, fill = bio_vel)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) + 
  #scale_fill_viridis(option = "cividis", name = "Flounder velocities") +
  scale_fill_gradient2(name = "km×decade<sup>-1</sup>") + 
  theme_sleek(base_size = 8) +
  labs(y = "") +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Flounder velocities")

p9 <- plot_map_fc + 
  geom_raster(data = velo2 |> filter(species == "Plaice"), aes(X*1000, Y*1000, fill = bio_vel)) +
  geom_polygon(data = domain, aes(X*1000, Y*1000),
               fill = NA, color = "red", size = 0.2) + 
  #scale_fill_viridis(option = "mako", name = "Plaice velocities") +
  scale_fill_gradient2(name = "km×decade<sup>-1</sup>") + 
  labs(y = "", x = "") +
  theme_sleek(base_size = 8) +
  theme(legend.position = c(0.19, 0.81),
        legend.key.height = unit(0.4, "line"),
        legend.key.width = unit(0.2, "line"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.title = ggtext::element_markdown(size = 6)) + 
  ggtitle("Plaice velocities")

(p1 + p2 + p3) / (p4 + p5 + p6) / (p7 + p8 + p9) + plot_annotation(tag_levels = "A")

ggsave(paste0(home, "/figures/bio_vars_space.pdf"), width = 17, height = 15, units = "cm", device = cairo_pdf)
```
